services:
  - type: web
    name: fake-news-detector
    env: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir --upgrade -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PIP_NO_CACHE_DIR
        value: true
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - app.py
        - requirements.txt
        - Procfile
        - models/**/*
        - templates/**/*
        - .gitignore
        - render.yaml
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 